# Generated by Django 5.2.8 on 2025-11-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cahier_des_charges', models.TextField(blank=True)),
                ('skills', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('github', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='projects/')),
                ('technologies', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
