# Generated by Django 5.2.8 on 2025-11-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
